from outcomeeng_testing.harnesses.instruction_block_harness_scenario_evidence import (
    test_symlinked_harness_instruction_files_materialize_as_regular_files as test_symlinked_harness_instruction_files_materialize_as_regular_files,
)
