"""Signal-safe verification recipe orchestrator for the marketplace.

Public surface:

- `Step` and `Recipe` — frozen dataclasses naming steps and recipe metadata
- `VALIDATION_RECIPE`, `TEST_RECIPE`, `CHECK_RECIPES` — declared recipe surfaces
- `*_ARGV` and output-label constants — source-owned values imported by tests
- `ProcessHandle`, `ProcessSpawner` — DI Protocols for subprocess creation
- `ProductionSpawner` — real `subprocess.Popen` adapter
- `run_recipe`, `run_check`, `run` — orchestration entry points
"""

from __future__ import annotations

from outcomeeng.validation._engine import (
    FAILURE_EXCERPT_LINE_LIMIT,
    FORWARDED_SIGNALS,
    FULL_LOG_LABEL,
    PHASE_COMPLETE,
    PHASE_PREFLIGHT,
    PHASE_RECIPE,
    POST_KILL_REAP_ATTEMPTS,
    RUN_FAIL_STATUS,
    RUN_PASS_STATUS,
    SIGNAL_GRACE_SECONDS,
    SIGNAL_POLL_INTERVAL_SECONDS,
    SPAWN_FAILURE_EXIT_CODE,
    SUMMARY_KEY_ARGV,
    SUMMARY_KEY_DURATION_SECONDS,
    SUMMARY_KEY_EXIT_CODE,
    SUMMARY_KEY_EXCERPT,
    SUMMARY_KEY_LABEL,
    SUMMARY_KEY_LOG_PATH,
    SUMMARY_KEY_PHASE,
    SUMMARY_KEY_PURPOSE,
    SUMMARY_KEY_RECIPE,
    SUMMARY_KEY_RECIPES,
    SUMMARY_KEY_STATUS,
    SUMMARY_KEY_STEPS,
    SUMMARY_KEY_SUMMARY_PATH,
    SUMMARY_KEY_VERIFICATION_TYPE,
    SUMMARY_PATH_LABEL,
    STEP_FAIL_STATUS,
    STEP_PASS_STATUS,
    run,
    run_check,
    run_recipe,
    terminate_process_group,
)
from outcomeeng.validation._model import (
    ProcessHandle,
    ProcessSpawner,
    Recipe,
    Step,
)
from outcomeeng.validation._spawner import ProductionSpawner
from outcomeeng.validation._summary_schema import (
    AD_HOC_SUMMARY_SCHEMA,
    CHECK_SUMMARY_SCHEMA,
    GATE_SUMMARY_SCHEMA,
    PRIMITIVE_SUMMARY_SCHEMA,
    assert_json_schema,
)
from outcomeeng.validation._steps import (
    ACTIONLINT_ARGV,
    CHECK_RECIPES,
    EVAL_PROMPTS_ARGV,
    EVAL_TRIGGER_WORKFLOW,
    EVAL_TRIGGERS_ARGV,
    FMT_CHECK_ARGV,
    HOOK_SAFETY_ARGV,
    MYPY_ARGV,
    PREFLIGHT_STEPS,
    PYRIGHT_ARGV,
    PYTHON_SOURCE_PATHS,
    PYTEST_ARGV,
    PURPOSE_CONFORMANCE,
    PURPOSE_CORRECTNESS,
    RECIPE_AD_HOC,
    RECIPE_CHECK,
    RECIPE_TEST,
    RECIPE_VALIDATION,
    RUFF_CHECK_ARGV,
    RUFF_FORMAT_ARGV,
    SHELLCHECK_ARGV,
    SPX_MARKDOWN_ARGV,
    TEST_RECIPE,
    TEST_STEPS,
    VALIDATION_RECIPE,
    VALIDATION_STEPS,
    VERIFICATION_TYPE_TESTING,
    VERIFICATION_TYPE_VALIDATION,
    test_recipe,
)
from outcomeeng.validation.selected_gate import (
    RECIPE_CHECK_FULL,
    SelectedGatePlan,
    SelectedGateStep,
    build_selected_gate_plan,
    collect_changed_paths,
    run_selected_check,
)

__all__ = [
    "ACTIONLINT_ARGV",
    "AD_HOC_SUMMARY_SCHEMA",
    "CHECK_RECIPES",
    "CHECK_SUMMARY_SCHEMA",
    "EVAL_PROMPTS_ARGV",
    "EVAL_TRIGGERS_ARGV",
    "EVAL_TRIGGER_WORKFLOW",
    "FMT_CHECK_ARGV",
    "FAILURE_EXCERPT_LINE_LIMIT",
    "FORWARDED_SIGNALS",
    "FULL_LOG_LABEL",
    "GATE_SUMMARY_SCHEMA",
    "HOOK_SAFETY_ARGV",
    "MYPY_ARGV",
    "PHASE_COMPLETE",
    "PHASE_PREFLIGHT",
    "PREFLIGHT_STEPS",
    "PHASE_RECIPE",
    "POST_KILL_REAP_ATTEMPTS",
    "PYRIGHT_ARGV",
    "PYTHON_SOURCE_PATHS",
    "PYTEST_ARGV",
    "PURPOSE_CONFORMANCE",
    "PURPOSE_CORRECTNESS",
    "RUFF_CHECK_ARGV",
    "RUFF_FORMAT_ARGV",
    "RECIPE_CHECK",
    "RECIPE_CHECK_FULL",
    "RECIPE_AD_HOC",
    "RECIPE_TEST",
    "RECIPE_VALIDATION",
    "RUN_FAIL_STATUS",
    "RUN_PASS_STATUS",
    "SIGNAL_GRACE_SECONDS",
    "SIGNAL_POLL_INTERVAL_SECONDS",
    "SPAWN_FAILURE_EXIT_CODE",
    "SHELLCHECK_ARGV",
    "SPX_MARKDOWN_ARGV",
    "SUMMARY_KEY_ARGV",
    "SUMMARY_KEY_DURATION_SECONDS",
    "SUMMARY_KEY_EXIT_CODE",
    "SUMMARY_KEY_EXCERPT",
    "SUMMARY_KEY_LABEL",
    "SUMMARY_KEY_LOG_PATH",
    "SUMMARY_KEY_PHASE",
    "SUMMARY_KEY_PURPOSE",
    "SUMMARY_KEY_RECIPE",
    "SUMMARY_KEY_RECIPES",
    "SUMMARY_KEY_STATUS",
    "SUMMARY_KEY_STEPS",
    "SUMMARY_KEY_SUMMARY_PATH",
    "SUMMARY_KEY_VERIFICATION_TYPE",
    "SUMMARY_PATH_LABEL",
    "STEP_FAIL_STATUS",
    "STEP_PASS_STATUS",
    "TEST_RECIPE",
    "TEST_STEPS",
    "VALIDATION_RECIPE",
    "VALIDATION_STEPS",
    "VERIFICATION_TYPE_TESTING",
    "VERIFICATION_TYPE_VALIDATION",
    "test_recipe",
    "terminate_process_group",
    "ProcessHandle",
    "ProcessSpawner",
    "ProductionSpawner",
    "PRIMITIVE_SUMMARY_SCHEMA",
    "Recipe",
    "Step",
    "SelectedGatePlan",
    "SelectedGateStep",
    "assert_json_schema",
    "build_selected_gate_plan",
    "collect_changed_paths",
    "run",
    "run_check",
    "run_recipe",
    "run_selected_check",
]
