"""Generate the plugin catalog section of README.md from manifests and frontmatter.

Reads the marketplace catalog at ``.claude-plugin/marketplace.json`` and, for
each plugin listed there, walks the authored source directory to collect:

  - skills from ``src/plugins/<name>/skills/*/SKILL.md``
  - the lifecycle skill emitted from ``src/templates/plugin/SKILL.md``
  - agents from ``src/plugins/<name>/agents/*.md``

Emits a Markdown block bounded by the sentinel comments

::

    <!-- BEGIN PLUGIN CATALOG (generated by `just docs` — do not edit) -->
    ...
    <!-- END PLUGIN CATALOG -->

Two modes:

* ``--write``  rewrites ``README.md`` in place between the sentinels.
* ``--check``  emits the regenerated content to stdout and exits non-zero if
  the on-disk README differs. Suitable as a CI / ``just check-full`` gate.

Default (no flag) prints the generated block to stdout without touching files.

Usage::

    uv run python -m outcomeeng.catalog.plugin_catalog [--write | --check]
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

from outcomeeng.distribution.build import _render_variables, render_text
from outcomeeng.distribution.contracts import (
    AGENTS_SUBDIR_NAME,
    MARKDOWN_FILE_SUFFIX,
    SKILL_DESCRIPTION_FIELD,
    SKILL_FILENAME,
    SKILL_NAME_FIELD,
    SKILLS_SUBDIR_NAME,
    Target,
)

BEGIN_SENTINEL = (
    "<!-- BEGIN PLUGIN CATALOG (generated by `just docs` — do not edit) -->"
)
END_SENTINEL = "<!-- END PLUGIN CATALOG -->"
SOURCE_PLUGINS_ROOT = Path("src") / "plugins"
MARKETPLACE_CATALOG_RELATIVE = Path(".claude-plugin") / "marketplace.json"
MARKETPLACE_PLUGINS_FIELD = "plugins"
PLUGIN_LIFECYCLE_TEMPLATE_RELATIVE = (
    Path("src") / "templates" / "plugin" / SKILL_FILENAME
)
PLUGIN_LIFECYCLE_SKILL_NAME_PATTERN = "{plugin_name}-plugin"
CATALOG_SKILL_KIND = "Skill"
CATALOG_AGENT_KIND = "Agent"
CATALOG_SUCCESS_EXIT_CODE = 0
CATALOG_DRIFT_EXIT_CODE = 1
LIFECYCLE_SKILL_DESCRIPTION_PREFIX = "ALWAYS invoke this skill to "
CATALOG_TARGET_LABELS: dict[Target, str] = {
    Target.CLAUDE: "Claude",
    Target.CODEX: "Codex",
}

# Description prefixes stripped from auto-emitted catalog rows. Each entry is
# matched case-sensitively at the start of the flattened description. The
# stripped form is then capitalized so the table cell starts with an uppercase
# letter.
STRIP_PREFIXES: tuple[str, ...] = (
    LIFECYCLE_SKILL_DESCRIPTION_PREFIX,
    "ALWAYS invoke this skill when ",
    "ALWAYS invoke this skill before ",
    "ALWAYS invoke this skill BEFORE ",
    "ALWAYS invoke BEFORE ",
    "ALWAYS invoke when ",
    "ALWAYS invoke before ",
    "Use this skill when ",
    "Use when ",
    "Use after ",
    "Use to ",
)


@dataclass(frozen=True)
class CatalogEntry:
    kind: str  # "Skill" | "Agent"
    name: str  # display name (with leading slash for skills, bare for agents)
    purpose: str  # one-line summary


@dataclass(frozen=True)
class PluginCatalog:
    name: str
    description: str
    entries: tuple[CatalogEntry, ...]


def _frontmatter_text(text: str) -> str:
    if not text.startswith("---\n"):
        return text
    end = text.find("\n---\n", 4)
    if end == -1:
        end = text.find("\n---", 4)
    if end == -1:
        return text
    return text[: end + len("\n---")]


def _render_catalog_frontmatter(
    text: str,
    target: Target,
    *,
    shared_root: Path | None,
    plugin_name: str | None = None,
) -> str:
    return render_text(
        _frontmatter_text(text),
        shared_root=shared_root,
        variables=_render_variables(target, plugin_name=plugin_name),
    )


def _catalog_frontmatter_variants(
    text: str,
    *,
    shared_root: Path | None,
    plugin_name: str | None = None,
) -> dict[Target, dict[str, str]]:
    return {
        target: parse_frontmatter(
            _render_catalog_frontmatter(
                text,
                target,
                shared_root=shared_root,
                plugin_name=plugin_name,
            ),
        )
        for target in Target
    }


def _shared_root_for_plugin(plugin_dir: Path) -> Path:
    return plugin_dir.parent.parent / "_shared"


def _catalog_name(
    variants: Mapping[Target, dict[str, str]],
    default: str,
) -> str:
    names = {
        target: meta.get(SKILL_NAME_FIELD) or default
        for target, meta in variants.items()
    }
    return render_target_values(names)


def render_target_values(values: Mapping[Target, str]) -> str:
    """Render one value directly or qualify divergent values by runtime target."""
    first = values[Target.CLAUDE]
    if all(value == first for value in values.values()):
        return first
    return "; ".join(
        f"{CATALOG_TARGET_LABELS[target]}: {value}" for target, value in values.items()
    )


def _catalog_purpose(variants: Mapping[Target, dict[str, str]]) -> str:
    purposes = {
        target: shorten_purpose(meta.get(SKILL_DESCRIPTION_FIELD, ""))
        for target, meta in variants.items()
    }
    return render_target_values(purposes)


def parse_frontmatter(text: str) -> dict[str, str]:
    """Return flat string values for the YAML frontmatter at the top of ``text``.

    Supports simple ``key: value`` pairs and block scalars introduced by ``>-``
    or ``>`` and ``|`` / ``|-``. Returns an empty dict if no frontmatter is
    found. Values for unrelated fields (lists, mappings) are skipped silently —
    this generator only needs ``name`` and ``description``.
    """
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        # Try trailing form without final newline
        end = text.find("\n---", 4)
        if end == -1:
            return {}
    block = text[4:end]
    out: dict[str, str] = {}
    lines = block.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if ":" not in line:
            i += 1
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if value in {">-", ">", "|", "|-"}:
            # Collect indented continuation lines.
            i += 1
            collected: list[str] = []
            while i < len(lines) and (
                lines[i].startswith((" ", "\t")) or not lines[i].strip()
            ):
                collected.append(lines[i].strip())
                i += 1
            out[key] = " ".join(part for part in collected if part)
            continue
        if value.startswith(("[", "{")):
            # Skip flow collections — not needed for the catalog.
            i += 1
            continue
        if (
            value.startswith(("'", '"'))
            and value.endswith(value[0])
            and len(value) >= 2
        ):
            value = value[1:-1]
        out[key] = value
        i += 1
    return out


def shorten_purpose(description: str) -> str:
    """Reduce a full skill or agent description to a single catalog cell."""
    flat = " ".join(description.split())
    for prefix in STRIP_PREFIXES:
        if flat.startswith(prefix):
            flat = flat[len(prefix) :]
            if flat:
                flat = flat[0].upper() + flat[1:]
            break
    # Trim at the first sentence boundary so the cell stays narrow. Skip
    # boundaries inside an unclosed parenthetical so the cell never ends with a
    # dangling "(".
    boundary_indexes: list[int] = []
    for terminator in (". ", " — ", "—", "; "):
        idx = flat.find(terminator)
        while idx != -1:
            if idx > 20 and flat[:idx].count("(") == flat[:idx].count(")"):
                boundary_indexes.append(idx)
                break
            idx = flat.find(terminator, idx + 1)
    if boundary_indexes:
        flat = flat[: min(boundary_indexes)]
    return flat.rstrip(" .")


def collect_skills(plugin_dir: Path) -> list[CatalogEntry]:
    skills_dir = plugin_dir / SKILLS_SUBDIR_NAME
    if not skills_dir.is_dir():
        return []
    entries: list[CatalogEntry] = []
    for skill_dir in sorted(skills_dir.iterdir()):
        skill_md = skill_dir / SKILL_FILENAME
        if not skill_md.is_file():
            continue
        variants = _catalog_frontmatter_variants(
            skill_md.read_text(encoding="utf-8"),
            shared_root=_shared_root_for_plugin(plugin_dir),
        )
        name = _catalog_name(variants, skill_dir.name)
        purpose = _catalog_purpose(variants)
        entries.append(
            CatalogEntry(kind=CATALOG_SKILL_KIND, name=f"`/{name}`", purpose=purpose)
        )
    return entries


def collect_lifecycle_skill(
    repo_root: Path,
    plugin_dir: Path,
    plugin_name: str,
) -> CatalogEntry:
    template_path = repo_root / PLUGIN_LIFECYCLE_TEMPLATE_RELATIVE
    variants = _catalog_frontmatter_variants(
        template_path.read_text(encoding="utf-8"),
        shared_root=_shared_root_for_plugin(plugin_dir),
        plugin_name=plugin_name,
    )
    name = _catalog_name(
        variants,
        PLUGIN_LIFECYCLE_SKILL_NAME_PATTERN.format(plugin_name=plugin_name),
    )
    return CatalogEntry(
        kind=CATALOG_SKILL_KIND,
        name=f"`/{name}`",
        purpose=_catalog_purpose(variants),
    )


def collect_agents(plugin_dir: Path) -> list[CatalogEntry]:
    target = plugin_dir / AGENTS_SUBDIR_NAME
    if not target.is_dir():
        return []
    entries: list[CatalogEntry] = []
    for path in sorted(target.iterdir()):
        if path.suffix != MARKDOWN_FILE_SUFFIX or not path.is_file():
            continue
        variants = _catalog_frontmatter_variants(
            path.read_text(encoding="utf-8"),
            shared_root=_shared_root_for_plugin(plugin_dir),
        )
        name = _catalog_name(variants, path.stem)
        purpose = _catalog_purpose(variants)
        entries.append(
            CatalogEntry(kind=CATALOG_AGENT_KIND, name=f"`{name}`", purpose=purpose)
        )
    return entries


def collect_plugins(repo_root: Path) -> list[PluginCatalog]:
    manifest_path = repo_root / MARKETPLACE_CATALOG_RELATIVE
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    plugins: list[PluginCatalog] = []
    for entry in manifest.get(MARKETPLACE_PLUGINS_FIELD, []):
        name = entry[SKILL_NAME_FIELD]
        plugin_dir = repo_root / SOURCE_PLUGINS_ROOT / name
        skills = collect_skills(plugin_dir)
        skills.append(collect_lifecycle_skill(repo_root, plugin_dir, name))
        skills.sort(key=lambda catalog_entry: catalog_entry.name)
        catalog = PluginCatalog(
            name=name,
            description=entry.get(SKILL_DESCRIPTION_FIELD, ""),
            entries=tuple(
                skills + collect_agents(plugin_dir),
            ),
        )
        plugins.append(catalog)
    plugins.sort(key=lambda p: p.name)
    return plugins


def render_table(entries: tuple[CatalogEntry, ...]) -> str:
    """Render a Markdown table whose column widths match dprint's expectations.

    dprint pads every cell to the widest cell in its column. Emitting tables
    in that canonical form keeps `just docs` output stable under `dprint fmt`.
    """
    if not entries:
        return "_No skills or agents._\n"
    headers = ("Type", "Name", "Purpose")
    rows = [(e.kind, e.name, e.purpose) for e in entries]
    widths = [
        max(len(headers[i]), *(len(row[i]) for row in rows))
        for i in range(len(headers))
    ]

    def row_line(cells: tuple[str, ...]) -> str:
        return "| " + " | ".join(c.ljust(w) for c, w in zip(cells, widths)) + " |\n"

    sep = "| " + " | ".join("-" * w for w in widths) + " |\n"
    return row_line(headers) + sep + "".join(row_line(r) for r in rows)


def render_catalog(plugins: list[PluginCatalog]) -> str:
    parts: list[str] = []
    parts.append(BEGIN_SENTINEL + "\n\n")
    for plugin in plugins:
        parts.append(f"### {plugin.name}\n\n")
        if plugin.description:
            parts.append(f"{plugin.description}\n\n")
        parts.append(render_table(plugin.entries))
        parts.append("\n")
    parts.append(END_SENTINEL + "\n")
    return "".join(parts)


def splice_catalog(readme: str, catalog: str) -> str:
    begin = _find_line_start(readme, BEGIN_SENTINEL)
    end = _find_line_start(
        readme,
        END_SENTINEL,
        start=begin + len(BEGIN_SENTINEL) if begin != -1 else 0,
    )
    if begin == -1 or end == -1 or end < begin:
        raise SystemExit(
            "README.md is missing the catalog sentinels. "
            f"Insert\n  {BEGIN_SENTINEL}\n  {END_SENTINEL}\n"
            "around the section you want regenerated.",
        )
    end_line_break = readme.find("\n", end)
    suffix_start = end_line_break + 1 if end_line_break != -1 else len(readme)
    return readme[:begin] + catalog + readme[suffix_start:]


def _find_line_start(text: str, marker: str, *, start: int = 0) -> int:
    index = text.find(marker, start)
    while index != -1:
        marker_end = index + len(marker)
        at_line_start = index == 0 or text[index - 1] == "\n"
        at_line_end = (
            marker_end == len(text)
            or text[marker_end] == "\n"
            or text.startswith("\r\n", marker_end)
        )
        if at_line_start and at_line_end:
            return index
        index = text.find(marker, index + 1)
    return -1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="rewrite README.md in place")
    mode.add_argument(
        "--check", action="store_true", help="exit non-zero if README.md is stale"
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="repository root (defaults to two levels up from this script)",
    )
    args = parser.parse_args(argv)

    plugins = collect_plugins(args.root)
    catalog = render_catalog(plugins)
    readme_path = args.root / "README.md"
    readme = readme_path.read_text(encoding="utf-8")

    if not args.write and not args.check:
        sys.stdout.write(catalog)
        return CATALOG_SUCCESS_EXIT_CODE

    new_readme = splice_catalog(readme, catalog)

    if args.check:
        if new_readme != readme:
            sys.stderr.write(
                "README.md plugin catalog is stale. Run `just docs` to regenerate.\n",
            )
            return CATALOG_DRIFT_EXIT_CODE
        return CATALOG_SUCCESS_EXIT_CODE

    if new_readme != readme:
        readme_path.write_text(new_readme, encoding="utf-8")
        sys.stdout.write(f"updated {readme_path}\n")
    else:
        sys.stdout.write("README.md catalog already up to date\n")
    return CATALOG_SUCCESS_EXIT_CODE


if __name__ == "__main__":
    raise SystemExit(main())
