"""Generate the plugin catalog section of README.md from manifests and frontmatter.

Reads the marketplace catalog at ``.claude-plugin/marketplace.json`` and, for
each plugin listed there, walks the authored source directory to collect:

  - skills from ``src/plugins/<name>/skills/*/SKILL.md``
  - agents from ``src/plugins/<name>/agents/*.md``
  - commands from ``src/plugins/<name>/commands/*.md``

Emits a Markdown block bounded by the sentinel comments

::

    <!-- BEGIN PLUGIN CATALOG (generated by `just docs` — do not edit) -->
    ...
    <!-- END PLUGIN CATALOG -->

Two modes:

* ``--write``  rewrites ``README.md`` in place between the sentinels.
* ``--check``  emits the regenerated content to stdout and exits non-zero if
  the on-disk README differs. Suitable as a CI / ``just check-full`` gate.

Default (no flag) prints the generated block to stdout without touching files.

Usage::

    uv run python -m outcomeeng.catalog.plugin_catalog [--write | --check]
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

from outcomeeng.distribution.build import render_text
from outcomeeng.distribution.contracts import Target
from outcomeeng.validation.spx_version import REQUIRED_SPX_VERSION

BEGIN_SENTINEL = (
    "<!-- BEGIN PLUGIN CATALOG (generated by `just docs` — do not edit) -->"
)
END_SENTINEL = "<!-- END PLUGIN CATALOG -->"
SOURCE_PLUGINS_ROOT = Path("src") / "plugins"
CATALOG_TARGET_LABELS: dict[Target, str] = {
    Target.CLAUDE: "Claude",
    Target.CODEX: "Codex",
}

# Description prefixes stripped from auto-emitted catalog rows. Each entry is
# matched case-sensitively at the start of the flattened description. The
# stripped form is then capitalized so the table cell starts with an uppercase
# letter.
STRIP_PREFIXES: tuple[str, ...] = (
    "ALWAYS invoke this skill when ",
    "ALWAYS invoke this skill before ",
    "ALWAYS invoke this skill BEFORE ",
    "ALWAYS invoke BEFORE ",
    "ALWAYS invoke when ",
    "ALWAYS invoke before ",
    "Use this skill when ",
    "Use when ",
    "Use after ",
    "Use to ",
)


@dataclass(frozen=True)
class CatalogEntry:
    kind: str  # "Skill" | "Agent" | "Command"
    name: str  # display name (with leading slash for skills/commands, bare for agents)
    purpose: str  # one-line summary


@dataclass(frozen=True)
class PluginCatalog:
    name: str
    description: str
    entries: tuple[CatalogEntry, ...]


def _frontmatter_text(text: str) -> str:
    if not text.startswith("---\n"):
        return text
    end = text.find("\n---\n", 4)
    if end == -1:
        end = text.find("\n---", 4)
    if end == -1:
        return text
    return text[: end + len("\n---")]


def _render_catalog_frontmatter(text: str, target: Target) -> str:
    return render_text(
        _frontmatter_text(text),
        variables={
            "target": target.value,
            "spx_floor": REQUIRED_SPX_VERSION,
        },
    )


def _catalog_frontmatter_variants(text: str) -> dict[Target, dict[str, str]]:
    return {
        target: parse_frontmatter(_render_catalog_frontmatter(text, target))
        for target in Target
    }


def _catalog_name(
    variants: Mapping[Target, dict[str, str]],
    default: str,
) -> str:
    names = {target: meta.get("name") or default for target, meta in variants.items()}
    first = names[Target.CLAUDE]
    if all(name == first for name in names.values()):
        return first
    return "; ".join(
        f"{CATALOG_TARGET_LABELS[target]}: {name}" for target, name in names.items()
    )


def _catalog_purpose(variants: Mapping[Target, dict[str, str]]) -> str:
    purposes = {
        target: shorten_purpose(meta.get("description", ""))
        for target, meta in variants.items()
    }
    first = purposes[Target.CLAUDE]
    if all(purpose == first for purpose in purposes.values()):
        return first
    return "; ".join(
        f"{CATALOG_TARGET_LABELS[target]}: {purpose}"
        for target, purpose in purposes.items()
    )


def parse_frontmatter(text: str) -> dict[str, str]:
    """Return flat string values for the YAML frontmatter at the top of ``text``.

    Supports simple ``key: value`` pairs and block scalars introduced by ``>-``
    or ``>`` and ``|`` / ``|-``. Returns an empty dict if no frontmatter is
    found. Values for unrelated fields (lists, mappings) are skipped silently —
    this generator only needs ``name`` and ``description``.
    """
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        # Try trailing form without final newline
        end = text.find("\n---", 4)
        if end == -1:
            return {}
    block = text[4:end]
    out: dict[str, str] = {}
    lines = block.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if ":" not in line:
            i += 1
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if value in {">-", ">", "|", "|-"}:
            # Collect indented continuation lines.
            i += 1
            collected: list[str] = []
            while i < len(lines) and (
                lines[i].startswith((" ", "\t")) or not lines[i].strip()
            ):
                collected.append(lines[i].strip())
                i += 1
            out[key] = " ".join(part for part in collected if part)
            continue
        if value.startswith(("[", "{")):
            # Skip flow collections — not needed for the catalog.
            i += 1
            continue
        if (
            value.startswith(("'", '"'))
            and value.endswith(value[0])
            and len(value) >= 2
        ):
            value = value[1:-1]
        out[key] = value
        i += 1
    return out


def shorten_purpose(description: str) -> str:
    """Reduce a full skill/agent/command description to a single catalog cell."""
    flat = " ".join(description.split())
    for prefix in STRIP_PREFIXES:
        if flat.startswith(prefix):
            flat = flat[len(prefix) :]
            if flat:
                flat = flat[0].upper() + flat[1:]
            break
    # Trim at the first sentence boundary so the cell stays narrow. Skip
    # boundaries inside an unclosed parenthetical so the cell never ends with a
    # dangling "(".
    for terminator in (". ", " — ", "—", "; "):
        idx = flat.find(terminator)
        while idx != -1 and idx <= 20:
            idx = flat.find(terminator, idx + 1)
        if idx != -1 and flat[:idx].count("(") == flat[:idx].count(")"):
            flat = flat[:idx]
            break
    return flat.rstrip(" .")


def collect_skills(plugin_dir: Path) -> list[CatalogEntry]:
    skills_dir = plugin_dir / "skills"
    if not skills_dir.is_dir():
        return []
    entries: list[CatalogEntry] = []
    for skill_dir in sorted(skills_dir.iterdir()):
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            continue
        variants = _catalog_frontmatter_variants(skill_md.read_text(encoding="utf-8"))
        name = _catalog_name(variants, skill_dir.name)
        purpose = _catalog_purpose(variants)
        entries.append(CatalogEntry(kind="Skill", name=f"`/{name}`", purpose=purpose))
    return entries


def collect_md_dir(
    plugin_dir: Path, subdir: str, kind: str, *, slash_prefix: bool
) -> list[CatalogEntry]:
    target = plugin_dir / subdir
    if not target.is_dir():
        return []
    entries: list[CatalogEntry] = []
    for path in sorted(target.iterdir()):
        if path.suffix != ".md" or not path.is_file():
            continue
        variants = _catalog_frontmatter_variants(path.read_text(encoding="utf-8"))
        name = _catalog_name(variants, path.stem)
        purpose = _catalog_purpose(variants)
        display = f"`/{name}`" if slash_prefix else f"`{name}`"
        entries.append(CatalogEntry(kind=kind, name=display, purpose=purpose))
    return entries


def collect_plugins(repo_root: Path) -> list[PluginCatalog]:
    manifest_path = repo_root / ".claude-plugin" / "marketplace.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    plugins: list[PluginCatalog] = []
    for entry in manifest.get("plugins", []):
        name = entry["name"]
        plugin_dir = repo_root / SOURCE_PLUGINS_ROOT / name
        catalog = PluginCatalog(
            name=name,
            description=entry.get("description", ""),
            entries=tuple(
                collect_skills(plugin_dir)
                + collect_md_dir(plugin_dir, "agents", "Agent", slash_prefix=False)
                + collect_md_dir(plugin_dir, "commands", "Command", slash_prefix=True),
            ),
        )
        plugins.append(catalog)
    plugins.sort(key=lambda p: p.name)
    return plugins


def render_table(entries: tuple[CatalogEntry, ...]) -> str:
    """Render a Markdown table whose column widths match dprint's expectations.

    dprint pads every cell to the widest cell in its column. Emitting tables
    in that canonical form keeps `just docs` output stable under `dprint fmt`.
    """
    if not entries:
        return "_No skills, agents, or commands._\n"
    headers = ("Type", "Name", "Purpose")
    rows = [(e.kind, e.name, e.purpose) for e in entries]
    widths = [
        max(len(headers[i]), *(len(row[i]) for row in rows))
        for i in range(len(headers))
    ]

    def row_line(cells: tuple[str, ...]) -> str:
        return "| " + " | ".join(c.ljust(w) for c, w in zip(cells, widths)) + " |\n"

    sep = "| " + " | ".join("-" * w for w in widths) + " |\n"
    return row_line(headers) + sep + "".join(row_line(r) for r in rows)


def render_catalog(plugins: list[PluginCatalog]) -> str:
    parts: list[str] = []
    parts.append(BEGIN_SENTINEL + "\n\n")
    for plugin in plugins:
        parts.append(f"### {plugin.name}\n\n")
        if plugin.description:
            parts.append(f"{plugin.description}\n\n")
        parts.append(render_table(plugin.entries))
        parts.append("\n")
    parts.append(END_SENTINEL + "\n")
    return "".join(parts)


def splice_catalog(readme: str, catalog: str) -> str:
    begin = readme.find(BEGIN_SENTINEL)
    end = readme.find(END_SENTINEL)
    if begin == -1 or end == -1 or end < begin:
        raise SystemExit(
            "README.md is missing the catalog sentinels. "
            f"Insert\n  {BEGIN_SENTINEL}\n  {END_SENTINEL}\n"
            "around the section you want regenerated.",
        )
    end_line_break = readme.find("\n", end)
    suffix_start = end_line_break + 1 if end_line_break != -1 else len(readme)
    return readme[:begin] + catalog + readme[suffix_start:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="rewrite README.md in place")
    mode.add_argument(
        "--check", action="store_true", help="exit non-zero if README.md is stale"
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="repository root (defaults to two levels up from this script)",
    )
    args = parser.parse_args(argv)

    plugins = collect_plugins(args.root)
    catalog = render_catalog(plugins)
    readme_path = args.root / "README.md"
    readme = readme_path.read_text(encoding="utf-8")

    if not args.write and not args.check:
        sys.stdout.write(catalog)
        return 0

    new_readme = splice_catalog(readme, catalog)

    if args.check:
        if new_readme != readme:
            sys.stderr.write(
                "README.md plugin catalog is stale. Run `just docs` to regenerate.\n",
            )
            return 1
        return 0

    if new_readme != readme:
        readme_path.write_text(new_readme, encoding="utf-8")
        sys.stdout.write(f"updated {readme_path}\n")
    else:
        sys.stdout.write("README.md catalog already up to date\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
