"""Generator-owned values for Codex cache preservation scenarios."""

PLUGIN_NAME = "spec-tree"
ORPHAN_PLUGIN_NAME = "removed-plugin"
UNINSTALLED_PLUGIN_NAME = "uninstalled-plugin"
OLDER_VERSION = "0.26.5"
CURRENT_VERSION = "0.26.6"
NEW_CURRENT_VERSION = "0.26.7"
NOT_INSTALLED_PLUGIN = "python"
NOT_INSTALLED_STALE_VERSION = "0.18.6"
NOT_INSTALLED_CURRENT_VERSION = "0.18.8"
